# Generated by Django 5.2.5 on 2025-08-12 16:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descreva o trabalho a ser realizado', verbose_name='Descrição do Serviço')),
                ('data_servico', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Serviço')),
                ('valor_acordado', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Acordado (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('contratante', models.ForeignKey(limit_choices_to={'role': 'contratante'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to=settings.AUTH_USER_MODEL, verbose_name='Contratante')),
                ('trabalhador', models.ForeignKey(limit_choices_to={'role': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_trabalhados', to=settings.AUTH_USER_MODEL, verbose_name='Trabalhador')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ControleJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('hora_pausa', models.DateTimeField(blank=True, null=True, verbose_name='Hora da Pausa')),
                ('hora_retorno', models.DateTimeField(blank=True, null=True, verbose_name='Hora do Retorno')),
                ('hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('total_horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Total de Horas Trabalhadas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_jornada', to='core.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Controle de Jornada',
                'verbose_name_plural': 'Controles de Jornada',
                'ordering': ['-data', '-hora_inicio'],
                'unique_together': {('servico', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota (1-5 estrelas)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário (opcional)')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('servico', 'avaliador')},
            },
        ),
    ]
