# Generated by Django 6.0.2 on 2026-04-06 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico_mensagem_controlejornada_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Deixe em branco se for apenas um dia', null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_servico',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
    ]
