# Generated by Django 4.2.27 on 2026-04-05 14:04

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('e_servico_risco', models.BooleanField(default=False, help_text='Marque para serviços que envolvem agrotóxico, motosserra ou máquinas pesadas', verbose_name='Serviço de Risco')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_servico', models.DateField(verbose_name='Data do Serviço')),
                ('valor_oferecido', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Oferecido (R$)')),
                ('vagas', models.PositiveIntegerField(default=1, verbose_name='Número de Vagas')),
                ('localizacao', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='aberta', max_length=15, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('contratante', models.ForeignKey(limit_choices_to={'role': 'contratante'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_publicadas', to=settings.AUTH_USER_MODEL, verbose_name='Contratante')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='core.tiposervico', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TrabalhadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_diario', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Diário (R$)')),
                ('disponivel_agora', models.BooleanField(default=False, verbose_name='Disponível Agora')),
                ('localizacao', models.CharField(blank=True, help_text='Cidade/Região onde atua', max_length=200, verbose_name='Localização')),
                ('descricao_experiencia', models.TextField(blank=True, verbose_name='Descrição da Experiência')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhadores', to='core.tiposervico', verbose_name='Tipo de Serviço')),
                ('trabalhador', models.ForeignKey(limit_choices_to={'role': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_oferecidos', to=settings.AUTH_USER_MODEL, verbose_name='Trabalhador')),
            ],
            options={
                'verbose_name': 'Trabalhador por Serviço',
                'verbose_name_plural': 'Trabalhadores por Serviço',
                'ordering': ['-disponivel_agora', 'trabalhador__first_name'],
                'unique_together': {('trabalhador', 'tipo_servico')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem de Apresentação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='Status')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.demanda', verbose_name='Demanda')),
                ('trabalhador', models.ForeignKey(limit_choices_to={'role': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_demandas', to=settings.AUTH_USER_MODEL, verbose_name='Trabalhador')),
            ],
            options={
                'verbose_name': 'Inscrição em Demanda',
                'verbose_name_plural': 'Inscrições em Demandas',
                'ordering': ['-data_inscricao'],
                'unique_together': {('demanda', 'trabalhador')},
            },
        ),
    ]
