# Generated by Django 5.2.5 on 2026-04-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servico_data_fim_alter_servico_data_servico'),
        ('core', '0004_tiposervico_demanda_trabalhadorservico_and_more'),
    ]

    operations = [
    ]
