# Generated by Django 5.2.5 on 2026-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_total_avaliacoes_alter_avaliacao_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('contratante', 'Contratante'), ('trabalhador', 'Trabalhador'), ('admin', 'Administrador')], default='trabalhador', max_length=12),
        ),
    ]
