# Generated by Django 5.2.5 on 2026-04-12 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_designacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Designação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=120, verbose_name='Motivo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvida', 'Resolvida'), ('ignorada', 'Ignorada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacao_admin', models.TextField(blank=True, default='', verbose_name='Observação do Admin')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Denúncia')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='contratos.contrato', verbose_name='Contrato')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciado')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['status', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogAcaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('suspender_usuario', 'Suspender Usuário'), ('reativar_usuario', 'Reativar Usuário'), ('alterar_contrato', 'Alterar Contrato'), ('resolver_denuncia', 'Resolver Denúncia'), ('criar_termo', 'Criar Termo'), ('editar_tipo_servico', 'Editar Tipo de Serviço')], max_length=30, verbose_name='Ação')),
                ('detalhes', models.TextField(verbose_name='Detalhes')),
                ('alvo_tipo', models.CharField(blank=True, default='', max_length=40, verbose_name='Tipo do Alvo')),
                ('alvo_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Alvo')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Log de Ação Admin',
                'verbose_name_plural': 'Logs de Ações Admin',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('contrato', 'Contrato'), ('servico', 'Serviço'), ('denuncia', 'Denúncia'), ('avaliacao', 'Avaliação')], default='sistema', max_length=20, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='Link')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['lida', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TermoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20, unique=True, verbose_name='Versão')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Termo de Uso',
                'verbose_name_plural': 'Termos de Uso',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
