# Generated by Django 5.2.5 on 2026-04-06 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tiposervico_demanda_trabalhadorservico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('participantes', models.ManyToManyField(related_name='conversas', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
                ('servico', models.ForeignKey(blank=True, help_text='Serviço que originou esta conversa (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='core.servico', verbose_name='Serviço Relacionado')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-ultima_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(help_text='Texto da mensagem', verbose_name='Conteúdo')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa', verbose_name='Conversa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
            },
        ),
    ]
