# Generated by Django 5.2.5 on 2026-04-08 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral')], default='integral', max_length=10, verbose_name='Turno')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('bloqueado', 'Bloqueado'), ('ocupado', 'Ocupado')], default='disponivel', max_length=10, verbose_name='Status')),
                ('motivo_bloqueio', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo do Bloqueio')),
                ('trabalhador', models.ForeignKey(limit_choices_to={'role': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL, verbose_name='Trabalhador')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['data', 'turno'],
                'unique_together': {('trabalhador', 'data', 'turno')},
            },
        ),
    ]
