# Generated by Django 6.0.2 on 2026-04-03 18:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_servico_mensagem_controlejornada_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do Contrato')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_assinatura', 'Aguardando Assinatura'), ('vigente', 'Vigente'), ('encerrado', 'Encerrado')], default='rascunho', max_length=30, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Contrato (R$)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('e_servico_risco', models.BooleanField(default=False, help_text='Marque se o serviço envolve atividades de risco.', verbose_name='Serviço de Risco?')),
                ('clausula_risco_texto', models.TextField(blank=True, default='', verbose_name='Cláusula de Risco')),
                ('declaracao_epi', models.TextField(blank=True, default='', verbose_name='Declaração de EPI')),
                ('declaracao_ferramentas', models.TextField(blank=True, default='', verbose_name='Declaração de Ferramentas')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='contratos/pdfs/', verbose_name='PDF do Contrato (Gerado)')),
                ('arquivo_pdf_assinado', models.FileField(blank=True, null=True, upload_to='contratos/pdfs_assinados/', verbose_name='PDF Assinado (Upload do Trabalhador)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('contratante', models.ForeignKey(limit_choices_to={'role': 'contratante'}, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_como_contratante', to=settings.AUTH_USER_MODEL, verbose_name='Contratante')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_formal', to='core.servico', verbose_name='Serviço')),
                ('trabalhador', models.ForeignKey(limit_choices_to={'role': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_como_trabalhador', to=settings.AUTH_USER_MODEL, verbose_name='Trabalhador')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_assinante', models.CharField(choices=[('contratante', 'Contratante'), ('trabalhador', 'Trabalhador')], max_length=12, verbose_name='Tipo de Assinante')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado?')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_contrato', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Assinatura de Contrato',
                'verbose_name_plural': 'Assinaturas de Contrato',
                'unique_together': {('contrato', 'tipo_assinante')},
            },
        ),
    ]
